site_name: 8SOAT - FIAP
plugins:
  - search
  - mermaid2
nav:
  - Início: index.md
  - Conteúdos:
    - Domain Driven Design: ./ddd/index.md
    - Docker: ./docker/index.md
    - Arquitetura de Software: ./software-architecture/index.md
    - Arquitetura Limpa: ./clean-architecture/index.md
    - Kubernetes: ./kubernetes/index.md
  - Ferramentas:
    - Indicações de Ferramentas: ./tools/index.md
  - Sobre: about.md
